### ISSUE TITLE
-march=armv7-a will cause ccls not to work

### ISSUE THREAD

**Issue by loongw** [MaskRay/ccls#107]
I am trying to use ccls with a cross-compiled project with compile_commands.json. There is a flags `-march=armv7-a` that cause ccls always to show 'xxx is being indexed'.

**Comment by bstaletic** [comment]
This happens because libclang doesn't support `-march=armv7-a` and using that flag leads to an AST deserialization error.

**Comment by loongw** [comment]
cquery works fine with the same compile_commands.json. is ccls possible to handle this issue?

**Comment by MaskRay** [comment]
`-march=armv7a` is not supported in clang. You may change it to `-target armv7a-linux-gnueabi`.

```zsh
clang -target armv7a-linux-gnueabi -E -dM -xc /dev/null

ln -s your_clang armv7a-linux-gnueabi-clang
./armv7a-linux-gnueabi -E -dM -xc /dev/null
```

A `compile_commands.json` entry looks like:
```javascript
    {
        "arguments": [ "armv7a-linux-gnueabi-clang++", "-c", "-o", "a.o", "a.cc" ], 
        "directory": "/tmp/d", 
        "file": "a.cc"
    }
```

**Comment by loongw** [comment]
Thank you guys for the patient explanation. It works now (with some random crash, rarely).

I was expecting ccls to works out-of-box.
In the future, can it be distributed with a default config which with a cquery-like blacklist or extraArgs ?

**Comment by Riatre** [comment]
With correct `--target`, `-march=` is supported.

```sh
$ clang++-7 --target=arm-none-linux-gnueabi -march=armv7-a -v -x c++ -
clang version 7.0.0-6 (tags/RELEASE_700/final)
Target: arm-none-linux-gnueabi
Thread model: posix
InstalledDir: /usr/bin
 "/usr/lib/llvm-7/bin/clang" -cc1 -triple armv7-none-linux-gnueabi -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name - -mrelocation-model static <...snipped...>
```

See how the triplet passed to cc1 is actually `armv7-none-linux-gnueabi`, so clangDriver did the work.

**Comment by MaskRay** [comment]
@loongw May I ask you to contribute a wiki page (cross compilation) for posterity since you've figured it out?

As @Riatre, it would be nice to work out-of-box but driver code is hard to write and maintain on the Clang API user side. As a quick example:

```
% strace -fe file -o >(grep /opt/rh/devtoolset) ~/llvm/Release/bin/clang++ -c a.cc
66559 stat("/opt/rh/devtoolset-7/root/usr", 0x7ffde47316c8) = -1 ENOENT (No such file or directory)
66559 stat("/opt/rh/devtoolset-6/root/usr", 0x7ffde47316c8) = -1 ENOENT (No such file or directory)
66559 stat("/opt/rh/devtoolset-4/root/usr", 0x7ffde47316c8) = -1 ENOENT (No such file or directory)
66559 stat("/opt/rh/devtoolset-3/root/usr", 0x7ffde47316c8) = -1 ENOENT (No such file or directory)
66559 stat("/opt/rh/devtoolset-2/root/usr", 0x7ffde47316c8) = -1 ENOENT (No such file or directory)
```

Extra fun in https://github.com/llvm-mirror/clang/tree/master/include/clang/Driver/Distro.h https://github.com/llvm-mirror/clang/tree/master/lib/Driver/ToolChains/Linux.cpp
When you specify an ARM triple, the detected toolchain path will change a bit.

Studying this piece of code strengthened my idea that user should just tweak `compile_commands.json` command line options by themselves. There is also nuance between the clang driver and clang tools (ccls, c-index-test, cquery, ...). The latter use CompilerInvocation APIs in a way similar to `clang -cc1` but lacks some handling.

On the other hand, cross compiling users have gone through the relatively complex toolchain usage process it is reasonable to expect to handle this configuration twiddling. A wiki page is very welcomed to help others :)

@Riatre ah yes, `-march` is done after triple selection.

**Comment by MaskRay** [comment]
This PR https://github.com/MaskRay/ccls/pull/171 may help.

```
% cat .ccls
%compile_commands.json
-target armv7a-linux-gnueabi
```
