### ISSUE TITLE
Call hierarchy should return position of function call.

### ISSUE THREAD

**Issue by Yanpas** [MaskRay/ccls#215]
If I open call hierarchy tree and jump to one of it's entries I go to function definition. It's not useful, I should jump to the line in code where the function is called.

**Comment by MaskRay** [comment]
It is useful when `hierarchy` is false (default): it returns `Location[]` (instead of a hierarchy `Out_cclsCall`).

For each `Location`, various clients fetch the whole line, which directly hints what the caller is. After jumping to the caller, since the cursor is on the identifier, the user may invoke `$ccls/call` immediately to obtain callers.

If really the call sites are needed, `textDocument/references` may be used. It is one-level, though.
