### ISSUE TITLE
ccls not completing system C headers

### ISSUE THREAD

**Issue by ahsanp** [MaskRay/ccls#260]
I'm using ccls with emacs lsp-mode. ccls does not seem to provide completion candidates for system headers such as math.h, stdio.h etc. Such as in the following screenshot
![screenshot from 2019-02-13 15-45-55](https://user-images.githubusercontent.com/16830690/52746219-a3299a00-2fa6-11e9-9a30-3e08248fd167.png)
Additionally when I do manually type in the header ccls does provide completion candidates from within the header file. Also find definition works for only some of the headers and functions within them.
I built ccls using the following:
```
cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$HOME/Projects/clang+llvm
cmake --build Release
```
I downloaded a prebuilt version of clang+llvm from llvm.org

Any idea how I could solve this problem?

Thank you!

**Comment by MaskRay** [comment]
The next major release of clang+llvm (8.0) will support builtin header file completion. There are two header completion backends in ccls:

* `#if LLVM_VERSION_MAJOR < 8`, use `ProjectProcessor::GetSearchDirs` and `include_complete.cc` (similar to cquery's approach). `compile_commands.json` and/or `.ccls` entries are preprocessed and the search directories are stored in `ccls::Project::Folder::search_dir2kind`. If you have neither `compile_commands.json` nor `.ccls`, header completion will be unavailable.
* otherwise, use builtin header file completion (`clang/lib/Sema`)

**Comment by ahsanp** [comment]
I'm sorry I don't quite understand what you meant here. 

I have been trying to compile llvm and clang using the instruction you mentioned. But I have been unable to compile it because it is not able to find target `cxx`. Is there a solution to solve this problem?

Also, I don't quite understand how to turn on completion if my clang+llvm is < 8.

Any help (especially with the llvm compilation) would be great!

Thank you!!

**Comment by MaskRay** [comment]
You need to have either `compile_commands.json` or `.ccls`

**Comment by ahsanp** [comment]
Great! Thank you for the response. 

I added .ccls file at the root of the project. Now ccls has started giving completions for system headers but it is still not giving completion candidates for header files that are part of the project.

Any idea how I can solve this?

Also would you happen to have a pointer to how I could compile the latest llvm+clang. The instructions on the ccls build instruction page don't seem to work. ninja cannot find the target 'cxx'.
