### ISSUE TITLE
Why not provide binary release?

### ISSUE THREAD

**Issue by kdurant** [MaskRay/ccls#291]
I (many people) have no ability to compile binaries

**Comment by MaskRay** [comment]
ccls depends on clang/llvm libraries, which are quite large. It would take lots of space to provide prebuilt binaries. 

Clang/llvm libraries are oftentimes available as system packages. wiki/Build has given instructions for a wide range of systems.

If someone doesn't know how to compile ccls with either system package or releases.llvm.org prebuilt binaries, I think ccls is not suitable for them.

**Comment by FirstLoveLife** [comment]
wiki/Build page is detailed enough for all OSes.

**Comment by FancyBanana** [comment]
I would like to reopen this issue because i've just spent couple of days figuring out hot to build llvm and ccls on Windows because commands provided in wiki did not work out for me.

>ccls depends on clang/llvm libraries, which are quite large. It would take lots of space to provide prebuilt binaries.  

It's not like github charges you for storage

>Clang/llvm libraries are oftentimes available as system packages. wiki/Build has given instructions for a wide range of systems.  

You said it yourself that on Windows we have to rebuild llvm

>If someone doesn't know how to compile ccls with either system package or releases.llvm.org prebuilt binaries, I think ccls is not suitable for them.

Again, not applicable for Windows.

In the age when you can get free CI/CD for you repo on github (travisci, circleci, azure pipelines) there's no excuse to not provide binaries when the build is so convoluted.

**Comment by XadE-Blue** [comment]
> I would like to reopen this issue because i've just spent couple of days figuring out hot to build llvm and ccls on Windows because commands provided in wiki did not work out for me.

@FancyBanana @kdurant They didn't work for me as well. [Try this guide](https://cxuesong.com/archives/1067)

> ccls depends on clang/llvm libraries, which are quite large. It would take lots of space to provide prebuilt binaries.

There's no excuse to not provide binaries. Currently, my llvm directory contains 33GB's of files, what can possibly be worse than that in terms of storage?

**Comment by FancyBanana** [comment]
@XadE-Blue you can quite simply provide the ccls binary and leave llvm+clang installation up to user.

**Comment by aviikc** [comment]
Would be very grateful you can provide some binaries of ccls. Specially win x64.

**Comment by benstaniford** [comment]
On my second evening of trying to get ccls to build...  binaries would be lovely..

**Comment by FancyBanana** [comment]
@benstaniford In case you are still trying, I can help.
I recompiled ccls recently because of the new version.
There is actually an .appveyor,yml CI config that builds the binary (oh the irony...).
I used Cmake GUI to configure the project:
![Screenshot (4)](https://user-images.githubusercontent.com/7935263/68718562-e783ae00-05a9-11ea-9112-31a9d7507eaf.png)
and built with `cmake --build build --target ccls --config Release`

**Comment by benstaniford** [comment]
@FancyBanana Aww, thanks for the thought.  I did finally get it to build by downloading the clang source and compiling that first.  It took a long time but it worked.  Unfortunately then I seemed to get bogged down with ccls taking 40 minutes at 100% CPU to finish processing my project (which builds in 5 minutes in visual studio) so I'm stuck again now.  Perhaps I need to play with my compilation database or some such..  ah well.  Life is never easy :-)

**Comment by ItsCubeTime** [comment]
This thread kinda speaks for itself as it is but, you shouldn't have to install and build 30 gb worth of binaries and source to install a language server.

The whole point of using a language server is after all to speed up your development workflow, not to slow it down. Making the whole project relatively useless unless you are building the language server for several people to use at once on your own end - something the developer should be doing.

**Comment by AqilCont** [comment]
When will prebuilt binaries be out???? If they can build it, why not just provide the binaries for Windows too :<

I don't want to spend like a week trying to figure out the cryptic wiki page when I just want to try this lang server out like wtf

**Comment by madscientist** [comment]
> When will prebuilt binaries be out????

I expect, never.  Certainly not until someone "out there" steps up and volunteers to provide them.

> something the developer should be doing

is totally wrong.  Developers develop the code.  Maintainers release the code.  Distributors build binary versions and make them available.

Often, the same people do development and maintenance.  Very rarely does the same person fill all three roles: it's hard for one person to deal with all the hassle of all three jobs, and still get anything productive done.

If you were using a GNU/Linux system like Debian or Ubuntu, you wouldn't have to build it yourself because ccls is already packaged by the distribution, for you:

```
~$ apt search ccls
Sorting... Done
Full Text Search... Done
ccls/focal-updates     C/C++/ObjC language server
```

If you want to use an operating system like Windows, then try looking for someplace that distributes pre-built binaries for Windows.  Here's one idea: https://community.chocolatey.org/packages/ccls  There may be others: I don't use Windows.

> In the age when you can get free CI/CD for you repo on github (travisci, circleci, azure pipelines) there's no excuse to not provide binaries when the build is so convoluted.

No excuse?  How about the "excuse" that getting these things set up and operating correctly is a lot of work, and it's a very different skill set than creating a C++ compiler or language server, and that maybe not everyone wants to spend their **_UNPAID_** free time messing around with that?   Maybe someone who thinks it's simple and straightforward, and even better who enjoys that work, should fork the repository and create the proper CI/CD pipeline files to get ccls to build, and then contribute that back again.

If the instructions are bad, maybe someone should fork the repository and fix them, then send in a PR for those changes.

It would be great if there were more people helping and fewer people whinging.

**Comment by AqilCont** [comment]
Is it possible to put the places where to find prebuilt binaries in the README? I think it would be pretty helpful, as I didn't know it was as easy as a chocolatey package for Windows. I don't think many people want to go through the hassle of building such a huge program when all they want is C++ autocomplete, types, etc. I am a sort of beginner of C++/C and I was told to try this out as it worked great for them.

**Comment by madscientist** [comment]
I'm sure it is possible... for someone who has tried it and found it to work and what steps are needed and can describe them.  I'm pretty sure MaskRay, like me, doesn't use Windows much if at all.  So someone who has done it could fork the ccls repo, enhance the README appropriately with instructions, and/or modify the wiki docs, and submit a PR.

**Comment by codingus-g** [comment]
Why does it require clang/llvm on windows when it can build with gcc on linux?
