### ISSUE TITLE
Performance issue of ccls

### ISSUE THREAD

**Issue by danleepw** [MaskRay/ccls#333]
Maybe i should open an official issue here. As I tried both cquery and ccls on my project, it seemed that ccls was much slower than cquery. I configured both of them to run on the same number of cores. ccls took more resource and time for initial cache building and parsing the file after i edited it.

Thanks for your help.

**Comment by MaskRay** [comment]
> ccls took more resource and time for initial cache building and parsing the file after i edited it.

I have the memory usage/cache size in mind and have done much to improve them. Do you have measurable numbers?

Once you saved the file, future saves will not require deserialization (`cache.retainInMemory: 1`), while ccls still has to do that.

Speaking of serialization, ccls' custom binary serialization is better than msgpack used in cquery. The msgpack was contributed by me so I'm pretty confident to state this.

Regarding memory usage:
* some `const char *` in `indexer.hh` optimizations are not implemented in cquery.
* ccls merges spell/extent -> some saving
* ccls handles multiple definition/insertion/deletion better -> uses more memory.
* There is some stuff that is indexed in ccls but not in cquery. I did lots of work on that libclang code.
* The recent `Change containers of Query*::Def fields from std::vector to ccls::Vec` also saves a lot.

If you have got measurable numbers, feel free to reopen it. For now, your conclusion is different from my understanding of both projects' code bases so I am closing it.

**Comment by danleepw** [comment]
I think memory size is not my concern. The resource I refer to is about CPU resource. In general, ccls took  longer time to finish the parsing than cquery. The time measure is about a 10~20 seconds longer on each single file update. 

Sorry if it makes you feeling uncomfortable on opening this issue. However, I would like to suggest to take this issue open if you are willing to keep this discussion. My primary goal is to give you some inputs to improve ccls.

**Comment by MaskRay** [comment]
Can you use `-log-file=/tmp/ccls.log -v=1` https://github.com/MaskRay/ccls/wiki/Debugging#logs and dump `"parse " "store index for"` lines in the log file?

> Sorry if it makes you feeling uncomfortable on opening this issue.

It's the lack of numbers that made me feeling uncomfortable. I receive more than 1 reports on average every day and many are invalid. I try my best to respond to them and address the issues if any. If the reports were invalid/ungrounded I would simply close them, as it would serve no purpose to keep open.

**Comment by danleepw** [comment]
As i mentioned, the resource is not about "memory" or "size of cache files". It is about all the CPU resources. Actually, cquery is faster than ccls in all projects, private or public, on my machine. If it is not in-sync to your other reports from "Other channels", then I should stop here.

Anyway, thanks for making ccls.

**Comment by MaskRay** [comment]
> It is about all the CPU resources.

If you provide the logs, I will appreciate it, otherwise I can only take your statement as ungrounded.

No cmake command line (what if you use Debug for one project and Release for the other? What if you specify `.cquery` but use `compile_commands.json` for the other? (cquery uses `.cquery` and ignores `compile_commands.json` if both exist; the behavior is different from ccls)

>  The time measure is about a 10~20 seconds longer on each single file update.

That would be unrealistic. It's more likely a problem somewhere else.

**Comment by myrgy** [comment]
cquery might be compiled with llvm6, while ccls use llvm7
I think good solution would be to give some data using some profiler

**Comment by dsxmachina** [comment]
Hi - i would like to make a performance measure, but since spacemacs starts my ccls server, i do not know where to put the `-log-file=/tmp/ccls.log -v=1` - can anyone give me a hint ? 

In some projects ccls runs on 100% on two CPU cores when i am just idling in my editor - i do not know if that is 'too much', but if it's just a config error or something it would be nice to bring that down :)
