### ISSUE TITLE
Can ccls be compiled with Clang/LLVM shared libs instead of static?

### ISSUE THREAD

**Issue by madscientist** [MaskRay/ccls#355]
### Observed behavior

I'm compiling ccls against the downloaded 7.0.1 distribution from releases.llvm.org.  This package contains both shared and static libraries.  When I compile ccls it links against the static libraries.

The resulting binary after being stripped is still 23M on my system.

### Desired behavior

I check in my tools into Git so they can be distributed around to all the developers.  Given the rapid pace of change/enhancement of ccls, I find myself needed to rebuild it relatively often.

If I could create ccls linked with Clang/LLVM shared libraries then the only thing that would need to be updated in Git would be the ccls binary itself but not the shared libraries, and ccls alone would (presumably) be much smaller which would be very nice.

It's not the biggest issue but it would help me out.

I made the fastest, hacky attempt to figure out how to link ccls with shared libs but couldn't come up with a link line that worked... so I'm not sure if it's even possible.  Does ccls use facilities that are not included in the Clang/LLVM shared libs but are only available in static libs?

I'm really unfamiliar with Clang/LLVM organization and structure so I'm not sure what's possible, but if it _should_ be possible I'm happy to do some cmake mods to get it working via a cmake option or similar.

### System information

* ccls version (`git describe --tags --long`): 0.20181225.9-37-g64f9dbdc
* clang version: 7.0.1 (tags/RELEASE_701/final)
* OS: GNU/Linux Ubuntu 18.04
* Editor: Emacs 26.1
* Language client (and version): lsp-mode-20190330.1241

**Comment by MaskRay** [comment]
> This package contains both shared and static libraries. When I compile ccls it links against the static libraries.

No, releases.llvm.org prebuilt archives provide only static libraries. To be more specific, `BUILD_SHARED_LIBS=OFF` is the default.

* `libLLVM*.a` `libclang*.a`
* `libLLVM*.so` `libclang*.so`, if you set `-DBUILD_SHARED_LIBS=ON`

`libclang.so` is different. It is almost always built as shared (`if(LLVM_ENABLE_PIC OR WIN32)`).

Some builds (e.g. Arch Linux `extra/clang` `extra/llvm`) set `-DLLVM_BUILD_LLVM_DYLIB=on -DLLVM_LINK_LLVM_DYLIB=on` and they will get `libLLVM.so` (unified `libLLVM*.a`). It also helps with the linker input/output sizes. There is no such thing named `-DLLVM_BUILD_CLANG_DYLIB=on` (I have to say the same `libclang.so` is a bit unfortunate: it might be better named `libclang-c.so`).

> The resulting binary after being stripped is still 23M on my system.

This matches the stripped size of mine: 25147944 bytes.

> I made the fastest, hacky attempt to figure out how to link ccls with shared libs but couldn't come up with a link line that worked... so I'm not sure if it's even possible. Does ccls use facilities that are not included in the Clang/LLVM shared libs but are only available in static libs?

I may be one of the few people who enjoy linking instead of hating it :)

```
LLVM=$(realpath ~/llvm)
cmake -H. -BDebug -G Ninja -DCMAKE_BUILD_TYPE=Debug \
 -DCMAKE_CXX_COMPILER=$LLVM/Stable/bin/clang++ \
 -DCMAKE_CXX_FLAGS=-gsplit-dwarf \
 -DCMAKE_EXE_LINKER_FLAGS='-fuse-ld=lld -Wl,--gdb-index' \
 -DCMAKE_EXPORT_COMPILE_COMMANDS=On \
 -DCMAKE_PREFIX_PATH="$LLVM/Release;$LLVM/Release/tools/clang;$LLVM;$LLVM/tools/clang"
```

* `-fuse-ld=ld`: lld is much faster than ld.bfd; clang has had this option for a long time. GCC 9 gets it too. On some Debian derivatives, they carry a GCC patch to enable this on GCC 7/8.
  This is probably the most important option to get faster linking.

In a debug build, I use:

* `-gsplit-dwarf=single`: a large chunk of debug info can be moved from the object file to a separate `.dwo` file to decrease the linker input size and thus speed up linking. The GCC implementation delegates to external programs `objcopy --extract-dwo` and `objcopy --strip-dwo` to achieve this. Clang has a native implementation if its integrated assembler is used (default on most architectures). `-gsplit-dwarf=single` is a relatively new (Nov 2018) clang option that places `.dwo` sections back into `.o` while keeping linker input size small (those `.debug*.dwo` sections are excluded (`SHF_EXCLUDE`) by the linker).
  [side note: clang `-gsplit-dwarf` was a no-op on OSes other than Linux/Fuchsia. 3 days ago I silently pushed a patch to let it benefit other ELF OSes (many *BSDs, etc)]
* `-Wl,--gdb-index`: When gdb loads ccls, it loads clang/llvm libraries linked by it. It may take a long time to parse DWARF tables in those libraries.
  As a side effect of `-gsplit-dwarf*`, `.debug_gnu_pub{names,types}` sections are built.
  gold and lld can build an accelarating table section `.gdb_index` with them to speed up gdb.
  This is very useful for llvm/clang shared libraries as otherwise the large bulk of debug info slows down gdb dramatically (`auto-solib-add` defaults to `on`).
  [side note: gdb doesn't have full DWARF 5 `.debug_names` support]
