### ISSUE TITLE
function-like macro is not defined

### ISSUE THREAD

**Issue by eran-** [MaskRay/ccls#358]
### Observed behavior

I'm working on [WebKit](https://github.com/WebKit/) with VS Code and for some reason ccls is ignoring and not indexing a macro that is used quite frequently in the project.

![Screenshot](https://i.imgur.com/coFfV6V.png)

[compile_commands.json](https://gist.github.com/eran-/4ea538b3e8f6a2c26989541d27bbf584) that I generated using the CMake `CMAKE_EXPORT_COMPILE_COMMAND` argument.

### Expected behavior

The macro should be recognized by ccls along with all the definitions that are included during preprocessing.

### System information

* ccls version (`git describe --tags --long`): master (64f9dbd)
* clang version: 8
* OS: MacOS Mojave 10.14.4
* Editor: VS Code

**Comment by MaskRay** [comment]
Can you give a bit more details about the filename that has the issue? Do you experience the issue with other files (source files, header files)?

> compile_commands.json that I generated using the CMake CMAKE_EXPORT_COMPILE_COMMAND argument.

`compile_commands.json` looks good.

**Comment by MaskRay** [comment]
Oh, see https://github.com/MaskRay/ccls/wiki/FAQ#diagnostics-in-headers

This file is not self-contained thus the issue.

**Comment by eran-** [comment]
Is there a way for diagnostics to overcome the use-before-define case? Something that I can manually configure?

**Comment by eran-** [comment]
So as far as I can tell, the problem occurs in the following scenario (I tried to minimize the example, excuse me for any embarrassing mistake):

macro.h:
```
#define ENABLED(x) 0;
```

A.h:

```
#if ENABLED(SOME_OPTION)

...

#endif
```

A.cpp:
```
#include "macro.h"
#include "A.h"

#if ENABLED(SOME_OPTION)

...

#endif

```

ccls will be totally fine with the use of `ENABLED` in `A.cpp`, but will raise the error in `A.h`.

**Comment by MaskRay** [comment]
> ccls will be totally fine with the use of ENABLED in A.cpp, but will raise the error in A.h.

Correct.

```cpp
// #include "macro.h"   // completion/diagnostics require you to define ENABLED
#if ENABLED(SOME_OPTION)
#endif
...

The indexer doesn't have the requirement.

**Comment by eran-** [comment]
> ```
> The indexer doesn't have the requirement.
> ```

Can I hint it somehow to be aware of this situation?

**Comment by madscientist** [comment]
It depends on your particular situation and what exactly you need.  Of course, the most direct answer is that if header file B.h requires a macro that is defined in header file A.h, then B.h should `#include "A.h"`.

So the question is, why is that not done in your headers?  If it's because someone forgot then the best answer is to add the missing #include.  If it's because there is some good reason, then the solution depends on the reason, and it depends on how complex the header is.

One option is to add a specific `-D` option to your `.ccls` file to force a specific definition always, during indexing.

Another option is to add a `%h %hpp --include=A.h` to your `.ccls` file which will force the `A.h` header to be always included before starting to index any header file.

If you must have the header included only sometimes but not all the time... I'm not sure how to address that.

**Comment by eran-** [comment]
> It depends on your particular situation and what exactly you need. Of course, the most direct answer is that if header file B.h requires a macro that is defined in header file A.h, then B.h should `#include "A.h"`.
> 

Of course, that's the obvious answer, but it is not feasible for a project in the sizes of the project that I'm working on.

> So the question is, why is that not done in your headers? If it's because someone forgot then the best answer is to add the missing #include. If it's because there is some good reason, then the solution depends on the reason, and it depends on how complex the header is.
> 

Honestly, I don't know what's the reason, but I'm pretty sure they have a good reason. But generally speaking, if they make sure they always include `A.h` before `<X>.h` in `<X>.cpp`, and they want to use a macro from `A.h` in `<X>.h`, after preprocessing that should be perfectly fine, shouldn't it?

> Another option is to add a `%h %hpp --include=A.h` to your `.ccls` file which will force the `A.h` header to be always included before starting to index any header file.
> 

This will possibly solve the

**Comment by madscientist** [comment]
There are legitimate reasons for not including headers: in my project we do this on purpose for good reasons.  That's why I requested a way to add arguments to the header index compile lines and MaskRay added %h/%hpp which is awesome.  However as I mentioned this might not work if you must have these headers only included in some places but not others or you have more complex requirements.  In our codebase it's a simple rule: A.h must be the first thing in every `.cpp` file and it must never be included in any `.h` file (the latter is really just a safety check to help enforce the former), so this feature works well for us.

As I said whether it works for you really depends on the details of your situation.  Hopefully it works!
