### ISSUE TITLE
Getting ld warnings when compiling with llvm-8

### ISSUE THREAD

**Issue by jvillasante** [MaskRay/ccls#369]
I'm getting this warnings when compiling with llvm-8 on MacOs, `ccls` successfully compiles (with warnings) but I does not really work with emacs afterwards.

```
ld: warning: direct access in function '__GLOBAL__sub_I_CommandLine.cpp' from file '/usr/local/opt/llvm/lib/libLLVMSupport.a(CommandLine.cpp.o)' to global weak symbol 'llvm::object_deleter<llvm::cl::SubCommand>::call(void*)' from file 'CMakeFiles/ccls.dir/src/main.cc.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```

This is how I'm doing the compilation:

```
  git clone --depth=1 --recursive https://github.com/MaskRay/ccls
  cd ccls
  cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++ -DCMAKE_PREFIX_PATH=/usr/local/opt/llvm -DBUILD_SHARED_LIBS=on
  cmake --build Release
```

**Comment by MaskRay** [comment]
You can change the title to mention this is Mac OS X specific. Please provide more information about your Mac OS X (the purpose of the issue template), and how you install llvm/clang.

> This was likely caused by different translation units being compiled with different visibility settings.

Append `-DCMAKE_CXX_FLAGS=-fvisibility=hidden`

> -DBUILD_SHARED_LIBS=on

This is not necessary because the ccls CMakeLists.txt builds just one executable, no libraries.
