### ISSUE TITLE
the std::cout should in but not in the candidate list

### ISSUE THREAD

**Issue by SuJinpei** [MaskRay/ccls#385]
### Observed behavior
Hi, I tried the spacemacs with the ccls to write c++ code. I found the std::cout not in the candidates' list just as below:
![2](https://user-images.githubusercontent.com/14050881/56887604-9e07c180-6aa4-11e9-8319-21469ba75b25.png)
And I manually completed the statement, an error message displayed just as below:
![1](https://user-images.githubusercontent.com/14050881/56887757-fb037780-6aa4-11e9-90c8-9bc6f99d41e7.png)

I also tried to compare with the cquery and found the cquery worked fine. The cquery shared same Clang library with ccls.
![3](https://user-images.githubusercontent.com/14050881/56887954-78c78300-6aa5-11e9-93e7-69a548e19f04.png)
![4](https://user-images.githubusercontent.com/14050881/56887959-7bc27380-6aa5-11e9-8520-fbb45cf420e7.png)

I also tested the ccls with another case,  and it works fine.
![image](https://user-images.githubusercontent.com/14050881/56888385-6863d800-6aa6-11e9-8d1e-4c8f78eaeb79.png)

my .spacemacs file, .ccls file and .cquery file

[spacemacs.txt](https://github.com/MaskRay/ccls/files/3126879/spacemacs.txt)
[ccls.txt](https://github.com/MaskRay/ccls/files/3126889/ccls.txt)
[cquery.txt](https://github.com/MaskRay/ccls/files/3126890/cquery.txt)

### Expected behavior

the std::cout should in the candidates' list since I have included `<iostream>`

### Steps to reproduce

1. install the spacemacs
2. install the ccls
3. enable ccls on c-c++ layer of the spacemacs
4. start emacs
5. open a cpp file and write code as below:
```
#include <iostream>

int main(int argc, char *argv[])
{
  std::cout << "hello\n";
  return 0;
}
```

### System information

* ccls version (`git describe --tags --long`): `0.20190314-5-ge496d4e5`
* clang version:  `clang version 9.0.0`
* OS:  `CentOS 7`
* Editor:  `GNU Emacs 26.2, Spacemacs develop branch`
* Language client (and version): `C++2a`

**Comment by MaskRay** [comment]
I cannot reproduce. Check if your `libstdc++` and `clang` are installed correctly.

> clang version 9.0.0

How did you install it?

**Comment by SuJinpei** [comment]
I think libstdc++ and clang are installed correctly since the cquery works fine.

below is how I built and install clang:
```
git clone https://git.llvm.org/git/llvm.git
git clone https://git.llvm.org/git/clang.git llvm/tools/clang
cd llvm
 
cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DLLVM_TARGETS_TO_BUILD=X86 -DCMAKE_CXX_COMPILER=$HOME/newlocal/gcc/bin/g++ -DCMAKE_C_COMPILER=$HOME/newlocal/gcc/bin/gcc -DCMAKE_INSTALL_PREFIX=$HOME/newlocal/llvm -DLLVM_ENABLE_RTTI=ON
 
cd Release
make clangFormat clangFrontendTool clangIndex clangTooling clang
```

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/wiki/Debugging#logs

`-v=1` or `-v=2` gives you the compiler command line.

```
09:46:45 indexer1         pipeline.cc:343 I parse /tmp/c/a.cc
  clang /tmp/c/a.cc --gcc-toolchain=/usr -working-directory=/tmp/c/
```

You may invoke that command to check if the file can be parsed.

**Comment by SuJinpei** [comment]
In my environment,  I got below:
```
11:35:36 indexer2         pipeline.cc:343 I parse /tmp/c/a.cc
  clang /tmp/c/a.cc -working-directory=/tmp/c/
```
the command's output as below:
```
clang /tmp/c/a.cc -working-directory=/tmp/c/
/tmp/a-7c987c.o: In function `main':
a.cc:(.text+0x18): undefined reference to `std::cout'
a.cc:(.text+0x2b): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
/tmp/a-7c987c.o: In function `__cxx_global_var_init':
a.cc:(.text.startup+0xf): undefined reference to `std::ios_base::Init::Init()'
a.cc:(.text.startup+0x15): undefined reference to `std::ios_base::Init::~Init()'
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by SuJinpei** [comment]
flow the instruction from https://llvm.org/docs/GettingStarted.html#getting-a-modern-host-c-toolchain to rebuild the gcc and the clang, then rebuild the ccls,  solve this issue.

**Comment by zombie110year** [comment]
I have installed ccls by `sudo pacman -S ccls-git` in ArchLinux and met the same problem.
What a pity that no "one click" solution there is.

**Comment by omrisim210** [comment]
Hi, I'm also facing similar difficulties and am struggling with debugging them.

I use Spacemacs on Arch Linux on WSL1 (Windows 10) and everything works great, apart from some members of `std` like `cout` and `cerr`, which ccls can't find.

The funny thing is, this is in my existing project which uses cmake with a submodule and a compilation database symlinked from the build directory to the project root as shown in the wiki.  
The submodule is configured so it can be used from cmake with `add_subdirectory`, and both completion and go-to-definition (on the `#include` line) work as expected.

Furthermore, I tried creating a dummy project to test things out: `cd /tmp; mkdir c; cd c; git init; touch .ccls`

```cpp
// a.cc
#include <stdio.h>
#include <iostream>
#include <stddef.h>

int main() {
  std::cout << "hi\n";
  return 0;
}
```

Everything is recognized and can be jumped to, including `cout`.
Just to make sure, I checked the output of `clang -v -fsyntax-only -x c++ /dev/null -target x86_64-linux-gnu`, and indeed it shows that clang _is_ using the gcc libs:

```
#include "..." search starts here:
#include <...> search starts here:
 /usr/sbin/../lib64/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../include/c++/9.2.1
 /usr/sbin/../lib64/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../include/c++/9.2.1/x86_64-pc-linux-gnu
 /usr/sbin/../lib64/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../include/c++/9.2.1/backward
 /usr/local/include
 /usr/lib/clang/9.0.1/include
 /usr/include
```

I also tried adding an empty `.ccls` file to my project's root (so I have both the ccls and the compile commands file), removing `compile_commands.json` and not having either file, it still doesn't seem to find the members of `std` defined in `iostream` (and that's just what I've seen, there might be more it can't find).

I'm sorry if the solution for this is already written elsewhere, I tried looking around the issues and the wiki and none of the solutions works or is relevant for my project.
I should also note I only tried doing this from Spacemacs, but since it works on a dummy project I see no reason for it to not work on my actual project unless one of the emacs modes can somehow configure ccls in a way that affects its results for this specific project, either on startup or by sending it some data (doesn't seem logical to me but I don't know too much about the LSP).
I can supply any other data that's needed.
