### ISSUE TITLE
invalid params of textDocument/codeAction

### ISSUE THREAD

**Issue by Aayush04** [MaskRay/ccls#395]
ccls language server is not accepting int for contex.diagnostics.code

Request:
```
{"jsonrpc":"2.0","id":4,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///root/lspData/workspace/c/9efd4849-ff2b-4253-afa0-86e457cb2c27/UserMainCode.c"},"range":{"start":{"line":9,"character":1},"end":{"line":9,"character":1}},"context":{"diagnostics":[{"range":{"start":{"line":9,"character":0},"end":{"line":9,"character":1}},"message":"control reaches end of non-void function","severity":2,"code":"2","source":"ccls"}]}}}
```

Response:
```
{"jsonrpc":"2.0","id":4,"error":{"code":-32602,"message":"invalid params of textDocument/codeAction: expected int for /context/diagnostics[0]/code"}}
```
Even though in LSP [documentation](https://microsoft.github.io/language-server-protocol/specification#diagnostic) diagnostics.code could be a number or string.

**Comment by MaskRay** [comment]
Sorry for my late response. (I'll close this as I don't think this will cause practical problems)

```cpp
// src/lsp.hh
struct Diagnostic {
  lsRange range;
  int severity = 0;
  int code = 0;  ///// it accepts int but not string
  std::string source = "ccls";
  std::string message;
  std::vector<DiagnosticRelatedInformation> relatedInformation;
  std::vector<TextEdit> fixits_;
};
```

Do you which client needs string code? This is usually not a problem because the codeAction message from the language client is derived from a previous messages from the language client. ccls serializes `code` as int so the client should forward `code` as an int.
