### ISSUE TITLE
Emscripten Toolchain C++ Header Includes

### ISSUE THREAD

**Issue by alexzielenski** [MaskRay/ccls#398]
### Observed behavior

I have started an Emscripten C++ project and I'm using ccls in vscode to develop it. I can't seem to get ccls to properly use the index C++ header files that I'm including. The headers are properly located, and I see logs such as these:

```
23:57:38                  pipeline.cc:382 I store index for /usr/local/Cellar/emscripten/1.38.31/libexec/system/include/libcxx/vector (delta: 0)
23:57:38                  pipeline.cc:382 I store index for /usr/local/Cellar/emscripten/1.38.31/libexec/system/include/libcxx/unordered_set (delta: 0)
23:57:38                  pipeline.cc:382 I store index for /usr/local/Cellar/emscripten/1.38.31/libexec/system/include/libcxx/tuple (delta: 0)
23:57:38                  pipeline.cc:382 I store index for /usr/local/Cellar/emscripten/1.38.31/libexec/system/include/libcxx/__tuple (delta: 0)
23:57:38                  pipeline.cc:382 I store index for /usr/local/Cellar/emscripten/1.38.31/libexec/system/include/libc/limits.h (delta: 0)
23:57:38                  pipeline.cc:382 I store index for /usr/local/Cellar/emscripten/1.38.31/libexec/system/include/libc/wchar.h (delta: 0)
23:57:38                  pipeline.cc:382 I store index for /usr/local/Cellar/emscripten/1.38.31/libexec/system/include/libc/features.h (delta: 0)
23:57:38                  pipeline.cc:382 I store index for /usr/local/Cellar/emscripten/1.38.31/libexec/system/include/libcxx/initializer_list (delta: 0)
23:57:38                  pipeline.cc:382 I store index for /usr/local/Cellar/emscripten/1.38.31/libexec/system/include/libcxx/cstddef (delta: 0)
23:57:38                  pipeline.cc:382 I store index for /usr/local/Cellar/emscripten/1.38.31/libexec/system/include/libcxx/memory (delta: 0)
23:57:38                  pipeline.cc:382 I store index for /usr/local/Cellar/emscripten/1.38.31/libexec/system/include/libcxx/iosfwd (delta: 0)
23:57:38                  pipeline.cc:382 I store index for /usr/local/Cellar/emscripten/1.38.31/libexec/system/include/libcxx/__bit_reference (delta: 0)
23:57:38                  pipeline.cc:382 I store index for /usr/local/Cellar/emscripten/1.38.31/libexec/system/lib/libc/musl/arch/emscripten/bits/alltypes.h (delta: 0)
23:57:38                  pipeline.cc:382 I store index for /usr/local/Cellar/emscripten/1.38.31/libexec/system/include/libcxx/__config (delta: 0)
```

When I open the header and switch the language to C++ (vscode doesn't detect the language since they have no extension) I see that ccls semantic highlighting is working properly, and that header's included headers are also found. 0 Problems reported in vscode.

However, when I attempt to use types to defined in the system headers, this happens:

<img width="576" alt="Screen Shot 2019-05-24 at 12 04 56 AM" src="https://user-images.githubusercontent.com/351783/58308891-94c5f800-7db7-11e9-9c6b-44a25434bab0.png">

Notice how there is no highlighting on the `unordered_set` type, and `ccls` inspection reports that the type of the field is `int`. This code compiles, and my editor reports no issues, but apparently the type is not being referenced correctly. Code completion about these fields also does not work, presumably since their type is `int`.

I've tried the below `.ccls` configuration

```
%clang++
-isystem/usr/local/Cellar/emscripten/1.38.31/libexec/system/include/libc
-cxx-isystem/usr/local/Cellar/emscripten/1.38.31/libexec/system/include/libcxx
```

### Expected behavior

I expected the semantic highlighting and code completion and to work for types from C++ library headers.

### Steps to reproduce

1. `brew install emscripten ccls` (I've also used my own compiled ccls copy with no success)
2. Set up `.ccls` as given, with version replaced possibly
3. Attempt to use types defined in files like `<vector>`

### System information

* ccls version 0.20190314
* clang version: 8.0.0
* OS: OS X 10.14.4
* Editor: vscode
* Language client (and version): vscode-ccls 0.1.26

**Comment by MaskRay** [comment]
See https://github.com/MaskRay/ccls/wiki/Build#macos

I don't have a Mac, but your `-cxx-isystem/usr/local/Cellar/emscripten/1.38.31/libexec/system/include/libcxx` looks weird to me. I expect it have path components `usr/include/c++/v1`

**Comment by alexzielenski** [comment]
I have attempted your suggestion and yielded same results, unfortunately. The headers are being properly located and included, their type information seems not to be made available, though?

**Comment by joelhock** [comment]
i wasn't familiar with emscripten, but i gather after looking a bit that it ships with its own clang toolchain, so having `-cxx-isystem/usr/local/Cellar/emscripten/1.38.31/libexec/system/include/libcxx` (or perhaps the more stable `-cxx-isystem/usr/local/opt/emscripten/libexec/system/include/libcxx`) might actually be the right thing to do here.  

i think that all might be a red herring here, though.  I get a similar `int` as the type instead of `std::unorderd_set` when I use an undefined type as the template parameter.  which is to say, i think that the real issue here is that `LayerProxy` is not recognized as a type.  There ought to be a diagnostic squiggly under the type, though, such as:

![image](https://user-images.githubusercontent.com/7648957/58767563-9bd8cd00-8552-11e9-8219-0d958e8f12aa.png)

I guess one way of helping diagnose if this is the real issue is if you can jump-to-definition on the `<unordered_set>` in the `#include` line.  if so, it's being found correctly.  Furthermore, if you can't jump-to-definition on `LayerProxy`, it might support my theory.

**Comment by alexzielenski** [comment]
Thanks for looking into this @joelhock. I checked just now and unfortunately I think your suspicions are not correct. I am able to jump to definition of both the LayerProxy and `undordered_set`: both at the include line and in the source itself.

<img width="428" alt="Screen Shot 2019-06-02 at 4 44 23 PM" src="https://user-images.githubusercontent.com/351783/58768836-afd1fe00-8555-11e9-900c-fef2cd964399.png">

<img width="594" alt="Screen Shot 2019-06-02 at 4 41 31 PM" src="https://user-images.githubusercontent.com/351783/58768818-95982000-8555-11e9-8f31-bd7c0716c7ef.png">

**Comment by igorcalabria** [comment]
Hi, I believe that I'm hitting the same problem but with another custom toolchain(devkitpro for arrm development). I have a working `compile_commands.json` and my .ccls looks like this 

```
%compile_commands.json
--target=arm-none-eabi
-isystem/opt/devkitpro/devkitA64/aarch64-none-elf/include/
-isystem/opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/10.2.0/include/
-isystem/opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/10.2.0/include-fixed/
-cxx-isystem/opt/devkitpro/devkitA64/aarch64-none-elf/include/c++/10.2.0/
```

`*.c` files works fine, but when editing cpp files, it reports std types missing. For example: 
![image](https://user-images.githubusercontent.com/2111602/91504229-e571ae00-e8a2-11ea-9aa5-c3fca606671d.png)
![image](https://user-images.githubusercontent.com/2111602/91504382-55803400-e8a3-11ea-9dbe-3ff989577eb7.png)

Jump to definition on `<string>` works just fine. I'm guessing that there's nothing wrong with ccls, but were missing some extra clang flag

**Comment by findNextStep** [comment]
> Hi, I believe that I'm hitting the same problem but with another custom toolchain(devkitpro for arrm development). I have a working `compile_commands.json` and my .ccls looks like this
> 
> ```
> %compile_commands.json
> --target=arm-none-eabi
> -isystem/opt/devkitpro/devkitA64/aarch64-none-elf/include/
> -isystem/opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/10.2.0/include/
> -isystem/opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/10.2.0/include-fixed/
> -cxx-isystem/opt/devkitpro/devkitA64/aarch64-none-elf/include/c++/10.2.0/
> ```
> 
> `*.c` files works fine, but when editing cpp files, it reports std types missing. For example:
> ![image](https://user-images.githubusercontent.com/2111602/91504229-e571ae00-e8a2-11ea-9aa5-c3fca606671d.png)
> ![image](https://user-images.githubusercontent.com/2111602/91504382-55803400-e8a3-11ea-9dbe-3ff989577eb7.png)
> 
> Jump to definition on `<string>` works just fine. I'm guessing that there's nothing wrong with ccls, but were missing some extra clang flag

As I know, in macOS we need add more compile command to ccls. the stl include path and clang resource dir is require
```
                "clang": {
                    "extraArgs": [
                        "-isystem",
                        "/usr/local/opt/llvm/include/c++/v1",
                    ],
                    "pathMappings": [],
                    "resourceDir": "/usr/local/opt/llvm/lib/clang/10.0.0"
                },
```

**Comment by igorcalabria** [comment]
@findNextStep Thanks for the suggestion, but I managed to figure it out. Almost everything on my side was wrong:
- missing some includes paths
- wrong order of includes
- wrong arch

About this issue, 
The best tip I can give is to replace the custom toolchain compiler with clang and try to compile a file with it. You'll get much better feedback for what's missing. Some useful commands:
Print system includes and definitions for the toolchain: `/opt/devkitpro/devkitA64/bin/aarch64-none-elf-g++ -dM -xc++ -E - -v < /dev/null`. This showed me that my include order was wrong and that I was missing `__DEVKITA64__` definition. Also, when cross compiling for another arch, builtins from gcc and clang may be different, so you can try replace the toolchain's include lib with clang so the correct builtins are used. This is kinda hacky, but since ccls is only used for indexing, it didn't cause any issues on my side. My final .ccls looks like this:

```
%compile_commands.json
-d__DEVKITA64__
--target=aarch64-none-elf
-nostdinc
-nostdinc++
-mcrc
-isystem/opt/devkitpro/devkita64/aarch64-none-elf/include/c++/10.2.0/
-isystem/opt/devkitpro/devkita64/aarch64-none-elf/include/c++/10.2.0/aarch64-none-elf
-isystem/opt/devkitpro/devkita64/aarch64-none-elf/include/c++/10.2.0/backward/
-isystem/home/igor/llvm-project-llvmorg-10.0.1/build/lib/clang/10.0.1/include/
-isystem/opt/devkitpro/devkita64/lib/gcc/aarch64-none-elf/10.2.0/include-fixed/
-isystem/opt/devkitpro/devkita64/aarch64-none-elf/include/
-isystem/opt/devkitpro/devkita64/aarch64-none-elf/include/machine
```
besides using this `.ccls`, I also had to exclude `-mtp=soft` from clang params. 

@MaskRay do you think its worth adding this info to the wiki? I'm not sure how common is setting up these toolchains with ccls but I think that some general information on how to figure out these details would be great. I could push a PR if you're interested

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/wiki/Build#macos has information about additional -isystem on macOS. Closing
