### ISSUE TITLE
It is not clear how to customize ccls 

### ISSUE THREAD

**Issue by shelper** [MaskRay/ccls#402]
for instance i have a very big project, and i dont want to index all as it crushes my system
so i saw i can only index the opened file by specifiying `{"index": {"initialBlacklist": ["."]}}`
the question is where should i put this option? just add a line of `--index initialBlacklist=["."]`with in the `.ccls` file?

**Comment by madscientist** [comment]
No, the `.ccls` file is for customizing how your code is indexed (what compiler flags are needed to find header files, command-line definitions of macros, etc.)  Think of it this way: the `.ccls` file could be checked in to your source code repository, because it contains information that is general to your project.

Options like `initialBlacklist` are specific to a given developer: some may want to index everything, some just one file at a time, some might want to omit some parts of the code and index other parts, etc.  That kind of thing is not appropriate to be checked into your source code repository: instead it should be customized by each developer in their own configuration.

As a result, these options are provided as initialization options when you start ccls, typically.  ccls is normally started by an LSP client.  Since you didn't fill out any of the template that describes what LSP client you're using we can't give you exact details on what you need to do: some LSP clients provide a facility for this.

If you wanted to start it from the command line, you want to use the `-init` command line option and pass it a JSON string; see the wiki page https://github.com/MaskRay/ccls/wiki/Customization

**Comment by shelper** [comment]
that is clear , thanks for clarify that!
