### ISSUE TITLE
CCLS detects error for even the most mundane/standard C++ statement

### ISSUE THREAD

**Issue by krishnakumarg1984** [MaskRay/ccls#452]
I am unable to use even standard C++ constructs like `cout` and `cin` since `CCLS` detects this as an error, flagging this to my linter.  The error persists even when I try `std::cout` explicitly. 

The error message is 
>no member named 'cout' in namespace 'std'

Here is the code snippet

```
#include <algorithm>
#include <cmath>
#include <iostream>
#include <string>
#include <vector>

using namespace std;

inline void keep_window_open() {
  char ch;
  cin >> ch;
}

int main(int argc, char *argv[]) {
  cout << "Hello, World!\n";
  std::cout << "Hello, World!\n";  // Trying std::cout to avoid warning
  return 0;
}
```

Why is this happening, and how to avoid it?

**Comment by qub1750ul** [comment]
Same here.
Also happens with std::vector, std::string_view, std::find and related variants.
But the fstream library constructs appear fine instead.

**Comment by madscientist** [comment]
It's happening because something is wrong with your installation or configuration.

Since you decided to delete all the aspects of the bug report template which would give us any information, instead of filling it all out, there's little we can say except: please read the wiki pages https://github.com/MaskRay/ccls/wiki especially the sections on project setup, customization, debugging, and the FAQ.  Hopefully the answers you need will be found there.

**Comment by MaskRay** [comment]
See https://github.com/MaskRay/ccls/wiki/FAQ#some-cc-headers-are-not-recognized

Just added some more stuff there. It is likely g++ is not properly installed.

**Comment by brown121407** [comment]
Hi @madscientist and @MaskRay,

This happens for me too. `cout`, `make_pair`, `sqrt` for example are signaled as "use of undeclared identifier".

I read the pages that you guys linked above, but to no avail. I'm using ccls in Emacs with lsp-mode and emacs-ccls (but I had the same problems in Vim too, yet I don't remember the exact setup). Header libraries get turned into links, so I can M-RET on `iostream` in `#include <iostream>` and it shows me `.../include/c++/iostream`.

Compiling the probrams works perfectly fine, so it's just a problem for CCLS to find *some* identifiers. This is just broken for C++. For C it works perfectly fine for any symbol.

I'm working on a GNU Guix System, here are the system details:
```
[user@host ~]$ guix describe
Generation 22   mar 02 2021 14:58:28    (current)
  guix f72caaf
    repository URL: https://git.savannah.gnu.org/git/guix.git
    branch: master
    commit: f72caafc6b50d4b19672dbe3fdcbb839f55951c8
[user@host ~]$ guix system describe
Generation 74   feb 27 2021 18:22:18    (current)
  file name: /var/guix/profiles/system-74-link
  canonical file name: /gnu/store/lqfn0qjwb52zd2jl51b1w9dqdzvwh4ff-system
  label: GNU with Linux 5.4.21
  bootloader: grub-efi
  root device: UUID: ecebc3b7-5ce9-4db4-9f38-a5f14692715f
  kernel: /gnu/store/1vvyvrl8sdi48x65xm482v1dnk9dfcbf-linux-5.4.21/bzImage
  channels:
    nonguix:
      repository URL: https://gitlab.com/nonguix/nonguix
      branch: master
      commit: 7428b7288eed0a50eed7a4fe373ac92c06a84588
    guix:
      repository URL: https://git.savannah.gnu.org/git/guix.git
      branch: master
      commit: 15c4b98daa4a4cb020f38531eb6be1557f7ee398
  configuration file: /gnu/store/77qh1vzcy20v7i71lb9in94fms0s78az-configuration.scm
```

Environment which should suffice to reproduce the issue:
```
guix environment --ad-hoc gcc-toolchain make bear emacs ccls emacs-lsp-mode emacs-lsp-ui emacs-ccls 
```

The `*ccls*` buffer in Emacs is empty, but `*ccls::stderr*` is full with stuff. There are a lot of lines, so I'll attach it as a file. I also attached my `compile_commands.json`, which is generated using `bear -- make`. (Extensions of uploads may be "incorrect" because GitHub doesn't allow arbitrary files).

[*ccls::stderr*.log](https://github.com/MaskRay/ccls/files/6068871/ccls.stderr.log)
[compile_commands.json.txt](https://github.com/MaskRay/ccls/files/6068878/compile_commands.json.txt)

**Comment by brown121407** [comment]
I tried replicating this on Artix, but there ccls works fine. Maybe it has something to do with how CCLS goes down the include paths in Guix? Would it hurt ccls if the include path is a link to another directory?
