### ISSUE TITLE
h files that are symbolic linked aren't shown

### ISSUE THREAD

**Issue by vushu** [MaskRay/ccls#463]
I am using Urho3d which have many h files that are symbolic linked, but these aren't shown, when using ccls, Is there a way to solve this?

**Comment by MaskRay** [comment]
> but these aren't shown

This currently cannot be fixed because clang does not record the original filenames of included files.

Say `/usr/include/c++/8.3.0` is a symlink to `/usr/include/c++/8`. In some cases a file may be referenced under both paths (probably due to bad `-I` usage) but you do not want to record the same physical file twice. I'm not sure what to do with these files.
