### ISSUE TITLE
Indexing llvm source in a stadalone project. 

### ISSUE THREAD

**Issue by hexhexd** [MaskRay/ccls#479]
Hello,

I'm currently working on my linker project and using the llvm libraries. I have built and installed llvm on my linux machine and using find_package(LLVM REQUIRED CONFIG) in Cmake. I can navigate to the definition of the llvm data structure using ccls and coc.nvim. Since I would love to be able to jump to the implementation of the data structure I wonder how I can instruct ccls to index the llvm source code that I had downloaded.

Thanks,
Alvin

**Comment by MaskRay** [comment]
To index a standalone LLVM:

```zsh
git clone git@github.com:llvm/llvm-project.git

# cmake -Hllvm -BDebug -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DLLVM_ENABLE_PROJECTS='llvm;clang' <other options>
ln -s llvm/compile_commands.json
```

To have a global view of both your projects and LLVM, i.e. to make `textDocument/definition` on an LLVM function jump to the definition, instead of the declaration (the LLVM headers are indexed even if you do not configure workspace folders), you'll have to ask your language client to use LSP 3.6.0 workspace folders (`interface InitializeParams`):

> If a client workspace consists of multiple roots then a server typically needs to know about this. The protocol up to now assumes one root folder which is announced to the server by the rootUri property of the InitializeParams. If the client supports workspace folders and announces them via the corresponding workspaceFolders client capability, the InitializeParams contain an additional property workspaceFolders with the configured workspace folders when the server starts.

**Comment by hexhexd** [comment]
Thanks for the detailed reply. Much appreciated!
