### ISSUE TITLE
ccls performance on large Translation Units

### ISSUE THREAD

**Issue by aravind2612krishna** [MaskRay/ccls#485]
### Observed behavior
ccls times out(5seconds) on completion for very large translation units (10,000 line +) with large number of headers.
I work with legacy code which has very large TUs and ccls times out a lot, is generally slow.
I have profiled the completion and attached an image here with the overall result.
I understand this is due to clang AST parse times, but any tips to increase performance will be appreciated.
![image](https://user-images.githubusercontent.com/3424615/65213381-92ed1680-dac3-11e9-9d0f-23920b517331.png)
I'd be happy to help with additional data/profiling.
Thank you for your efforts.

### System information

* ccls version (`git describe --tags --long`): 0.20190823.2-0-ga5b00dd
* clang version: llvmorg-9.0.0-rc4-0-g127240a
* OS: Windows
* Editor: neovim v0.4.2
* Language client (and version): coc.nvim 0.0.74-e8e583c8e0

**Comment by MaskRay** [comment]
ccls indexing performance has been greatly improved in the 0.20190823.2 release. The error you saw probably doesn't matter. It just means that some requests were dropped just because the file hasn't been indexed yet. You can wait a few more seconds and these requests (`textDocument/hover` `textDocument/definition` `textDocument/references` ...) should work.

Alternatively, if you don't want to see dropped requests, set the initialization option `request.timeout`:

```c
  struct Request {
    // If the document of a request has not been indexed, wait up to this many
    // milleseconds before reporting error.
    int64_t timeout = 5000;
  } request;
```

This means ccls may not respond in 5 seconds. You may have to change the timeout setting in your client accordingly (if such timeout exists).

**Comment by aravind2612krishna** [comment]
Thanks, I'll try tweaking the initialization option.
I'm reporting on a fully indexed file, Completion requests consistently take > 5 seconds due to the large size of the translation unit.
I notice very snappy performance on smaller TUs.
I realize this might be the clangAST parsing that is the bottleneck.
I used Intel's VTune to profile

**Comment by MaskRay** [comment]
> I realize this might be the clangAST parsing that is the bottleneck.

Yes :) I believe there is not much to optimize on ccls' side.

> Completion requests consistently take > 5 seconds due to the large size of the translation unit.

It takes a bit longer for the initial completion/diagnostics. Subsequent requests can leverage clang's preamble optimization, so you should observe snappier completion/diagnostics afterwards.
