### ISSUE TITLE
socket mode?

### ISSUE THREAD

**Issue by unphased** [MaskRay/ccls#491]
Feature request:

### Observed behavior

Between 1.3GB and 3GB of RAM are consumed by every ccls process on my large codebase. So, each new vim/nvim instance opening a file in the codebase will consume at least this much more RAM.

### Expected behavior

ccls can be run independently, and clients (coc.nvim for example) can be configured to connect to it using a socket, so that ccls is not spawned by the client. 

See https://github.com/neoclide/coc.nvim/issues/861

**Comment by MaskRay** [comment]
I think this ("socket language server") is a language client feature. ccls uses stdin/stdout. The language client can just connect stdio/stdout to a socket.

See also https://github.com/MaskRay/ccls/issues/277#issuecomment-465822200

**Comment by doesntcount** [comment]
I'm not sure I agree that this is a language client feature. The fact that ccls can't currently service multiple clients (given that it interfaces over stdin/stdout) means that it's not actually a server. This feature request I believe is validly requesting that it behave more like a traditional server in a generic software sense.

**Comment by Riatre** [comment]
> The fact that ccls can't currently service multiple clients

Have ccls serving multiple clients via some form (be it socket or not) does not really help here. 

The underlying protocol, Language Server Protocol, is designed around the idea "there will be ONLY ONE client talking to one server instance at the same time". Even if the server takes multiple "connections", most requests still requires all clients kept in sync at least. It is designed as such because other editors does not really allow the same "one editor instance per buffer" model as vim, and even with vim people tend to not use it in this way.

Feel free to yell at upstream if you like: https://github.com/microsoft/language-server-protocol/issues
