### ISSUE TITLE
Request textDocument/definition failed - not indexed

### ISSUE THREAD

**Issue by loblik** [MaskRay/ccls#499]
I have following versions of coc and ccls.

coc.nvim version: 0.0.74-5445f64a56
ccls version 0.20190823-4
clang version 8.0.1-3+b1 (tags/RELEASE_801/final)

I've generated compile_commands.json using clang and ccls seems to be loading it and indexing files. However when I try to go to definition using coc.nvim I got following error in :CocInfo :

```
Request textDocument/definition failed.
Message: not indexed
Code: -32600 
```
Anything I can do to solve this?

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/wiki/Project-Setup
https://github.com/MaskRay/ccls/wiki/Debugging

Please also search for past issues.

**Comment by MaskRay** [comment]
> As I have not got an answer in #499 I will try again. I have a compile_commands.json which should be valid (as cmake is able to build the project using that).
>
> However ccls is not able to index the files. There are only parse info messages in the ccls log file but no lines with store message. I've read somewhere missing store line means indexing was not done on that file.
>
> Is there a way to find out file was not parsed and indexed succesfully without adding prints to the source code?

You need to provide more detail as the issue template *mandates*.

**Comment by loblik** [comment]
It seems the indexer does not like the g++ I have in compile_commands. It's a cross-compiler for arm board (but should be basically upstream gcc). Indexer is giving up at clang->hasTarget() check in index function. Not sure what exactly does not like there. If I produce compile_commands using host compiler index works.

Maybe I will look at it when I have more time.

**Comment by Redrield** [comment]
I may have found a solution to this, and similar issues all arising from trying to use ccls with embedded toolchains. I've summarized everything here as this issue identifies the problematic code in ccls.

I have a project with a compile_commands generated by `arduino-cli`, The arguments specified use, a cross compiler version of g++ (In this case, specifically for esp32)

The `CompilerInvocation` used by the `CompilerInstance` is generated from `buildCompilerInvocation`, where it infers a target triple based on the program name passed in args[0]. In the case of the cross compiler that generated my compile_commands, that is `xtensa-esp32s3-unknown-elf`. That target triple is passed along to `TargetInfo::CreateTargetinfo`, where it fails because libclang doesn't recognize the triple (https://github.com/llvm/llvm-project/blob/main/clang/lib/Basic/Targets.cpp#L784). `CreateTargetInfo` short circuits, returning null, which is passed to setTarget, which then leads to `hasTarget` being false, forwards the error upwards, leading to the symptom of an internal error with message "Failed to index {source file}".

I've found a workaround by overriding the target triple inferred from the compiler file with the libllvm default for the host arch, using `llvm::sys::getDefaultTargetTriple()`. At a quick glance, this doesn't seem to lead to any discrepancies for the purposes of a language server, but might be something to look into before actually mainlining something like that. (Note that I believe this approach is essentially doing in code what @loblik did to resolve their issue here, as well as what @kovalcikr did in #746. Forcing ccls to use the system compiler (and target the host) for the indexing bypasses any issues caused by libclang not recognizing an obscure target.)

The patch that seems to fix this can be found at https://github.com/Redrield/ccls/tree/fix/host-triple-when-unknown. (Ignore the main branch, it's a mess due to the way I was investigating this). I'd be happy to open a proper PR for it if this is something that could be merged.
