### ISSUE TITLE
global index cache

### ISSUE THREAD

**Issue by maddanio** [MaskRay/ccls#504]
This is a question/suggestion. In order to get ccls to use less resources I was wondering if it is possible to share caches in the way ccache does, i.e. by hashing the file and the command line options. This would help in two ways:
- system header file indices (added via compdb) could be shared between projects
- indices can be shared between branches of a project in different checkouts, where many files and the command line options are unchanged

**Comment by MaskRay** [comment]
> system header file indices (added via compdb) could be shared between projects

No. Many command line options (`-I` `-isystem` `-D`) can affect index results. ccls would have to use a mechanism like C++ module cache to share indices of system headers. This optimization will not be very useful because system header file is only indexed once for a project.

> indices can be shared between branches of a project in different checkouts, where many files and the command line options are unchanged

The cache file is considered stale if

* The timestamp of the file, or any of its dependency has changed. See `pipeline.cc:indexer_Parse`.
* The clang command line options have changed. See  `pipeline.cc:cacheInvalid`.

Added to https://github.com/MaskRay/ccls/wiki/FAQ
