### ISSUE TITLE
Detect LocationLink client capability

### ISSUE THREAD

**Issue by rwols** [MaskRay/ccls#533]
### Observed behavior

ccls uses LocationLink, but does not check wether a client supports it via clientCapabilities.textDocument.declaration.linkSupport.

### Expected behavior

Upon requesting textDocument/{definition,declaration} et al, ccls should respond with  Location | Location[] if the client does not advertise clientCapabilities.textDocument.declaration.linkSupport.

### Steps to reproduce

1. Install SublimeText
2. Install LSP through package control
3. Set up ccls
4. Open a c/c++ project
5. goto definition

### System information

* Editor: SublimeText
* Language client (and version): https://github.com/tomv564/lsp master branch

**Comment by rwols** [comment]
fixed in master by https://github.com/tomv564/LSP/pull/796, but this language should still detect features.

**Comment by MaskRay** [comment]
The language server could do that, but that probably just added some backward compatibility code that increased maintenance burden. Not supporting it may cause some trouble to clients that do not follow the latest specification. May feeling is that since the majority of clients support LocationLink anyway, it is not very necessary to have the non-LocationLink code path in the server.
