### ISSUE TITLE
Reported crashes on Fedora 31 in clang::NestedNameSpecifier::getKind() const

### ISSUE THREAD

**Issue by D4N** [MaskRay/ccls#550]
Hi,

I have received an automated report about ccls crashing on Fedora 31 in `clang::NestedNameSpecifier::getKind() const`: https://retrace.fedoraproject.org/faf/reports/2767022/ (link includes a backtrace).

The crash appears to have occurred about 40 times, but unfortunately I have not received a bug report, thus I cannot provide you with a reproducer. If it is impossible to deduce anything useful from the report, please feel free to close this issue.

### System information

* ccls version (`git describe --tags --long`): 0.20190823.5
* clang version: 9.0.0
* OS: Fedora 31
* Editor: n/a
* Language client (and version): n/a

**Comment by D4N** [comment]
Another automated backtrace just poped up: https://retrace.fedoraproject.org/faf/reports/2767023/. The backtrace is different, but it ends in the same clang function (`clang::NestedNameSpecifier::getKind() const`) so maybe it is a clang issue after all.

**Comment by MaskRay** [comment]
```
21 llvm::CrashRecoveryContext::RunSafely
22 ccls::idx::index
```

`llvm::CrashRecoveryContext::RunSafely` installs SIGABRT/SIGBUS/SIGFPE/SIGILL/SIGSEGV/SIGTRAP handlers and can protect some types of crash. (I know that stack overflow may not be detected because there is no alternative stack setup.) There is too little information we can deduce from the report, which only includes the stack trace.

There may be a bug in the clang 9 package. I don't know whether it is still in git HEAD or not. Before we know the source code and command line that triggered the SIGSEGV, unfortunately we cannot do anything.
