### ISSUE TITLE
[feature] support clang-tidy

### ISSUE THREAD

**Issue by findNextStep** [MaskRay/ccls#568]
can we just use clang-tidy as a Warning source
as the clang-tidy need compile-commands.json and hard to use independent
https://clang.llvm.org/extra/clang-tidy/
clangd support --clang-tidy to enable clang-tidy check

**Comment by findNextStep** [comment]
it seem that it too hard to make clang-tidy build-in 
![image](https://user-images.githubusercontent.com/26270464/74104568-fbcb4d00-4b90-11ea-9209-b52d2def0154.png)

**Comment by xbreak** [comment]
@findNextStep: Could you elaborate what the issue(s) were? Having an option to enable clang-tidy feedback would be very welcome for me.

**Comment by findNextStep** [comment]
> @findNextStep: Could you elaborate what the issue(s) were? Having an option to enable clang-tidy feedback would be very welcome for me.

I try to read the source code of clangd , the clangd just compile with clang-tidy and share same include file, if we just call clang-tidy out side the ccls, it`s no different to use other plugin to enable clang-tidy.
the clangd work like 
clang -> clangd
          -> clang-tidy
it impossble to done in ccls

**Comment by xbreak** [comment]
Ok, thanks for the clarification!

**Comment by MaskRay** [comment]
clang-tidy does not expose its headers. In a released package, one can find clang and LLVM headers but not clang-tools-extra's. clangd does `#include "../clang-tidy/ClangTidyDiagnosticConsumer.h"`. It works because the directory is beside `clang-tidy`. It is indeed very difficult for an out-of-tree project (ccls) to get that feature.

The other thing is that it is unclear integrating clang-tidy in a language server is beneficial. The tool can perfectly run standalone. Integrating can save some setup but not beyond that. It can also be very CPU consuming if clang-tidy checks are fired on `textDocument/didChange` events.
