### ISSUE TITLE
How to install?????

### ISSUE THREAD

**Issue by pianocomposer321** [MaskRay/ccls#569]
The instructions are _very_ confusing. I am trying to build and install on windows. I have installed cmake and llvm (via chocolaty), and then I ran "cmake --build . --config Release --target install". Output:
Error: could not load cache

What am I doing wrong?

**Comment by Nazeehe** [comment]
I hear you. At first it really was confusing but after doing it a few times now, it's actually pretty straight forward. So here's what I do:

First off, you need to have the following:
- Get Visual Studio 2017 Community edition installed. 2019 will have llvm complain that the 2019 compiler miscompiles llvm. You can get around it, but having 2017 just works. I googled "download Visual studio 2017 community" and got installed. 
- Get cmake from Choco as you did. That's awesome!
- You need to get llvm and build it from source on Windows. 

Test that you're set up right:
- Open Command prompt for VS 2017 and try this:
> cmake
runs? good. 
now:
> ninja
Runs? good. If neither run, they are simply not in your path but choco does the right thing so you're good probably.

The process:

So here's what I did (which is basically the instructions in the Build section):

- Clone LLVM:
git clone https://github.com/llvm/llvm-project.git
cd llvm-project

Now we build it: (run both commands in sequence - cmake then ninja)

cmake -Hllvm -BRelease -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_ENABLE_PROJECTS=clang

ninja -C Release clangFormat clangFrontendTool clangIndex clangTooling clang

This will take a while. Go do something else :) 

Alright! Now we build ccls!

Clone it:
git clone --depth=1 --recursive https://github.com/MaskRay/ccls
cd ccls

Build it:

NOTE/IMPORTANT!!: See the following cmake command? It has a bunch of paths at the end that you need to modify to match YOUR machine. It's straightfoward: you cloned llvm earlier, I am going to assume you did that in your C:\ drive. So it should be in C:\llvm-project. Now change ALL the instances of D:/llvm/ below to C:/llvm-project/ (or whatever your path is)

cmake -H. -BRelease -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_PREFIX_PATH="D:/llvm/Release;D:/llvm/Release/tools/clang;D:/llvm;D:/llvm/tools/clang"

ninja -C Release

Done. You have ccls.exe under <path to ccls folder>\Release\ccls.exe

Best of luck :)

**Comment by Smit-tay** [comment]
Also agree - I have read through [the install instructions](https://github.com/MaskRay/ccls/wiki/Visual-Studio-Code) several times and am left scratching my head as to how anyone else managed to get this installed - or configured.

What does this mean:

> To load vscode-ccls without installing:
> 
> -     code vscode-ccls      ?????
> -     Press F5
> 

What does the instruction "code vscode-ccls" mean ?  How do I do that step ?   Which menu option do I use?
What does it mean to load it without installing it ?

I appreciate that people have gone to the effort of making tools like this available for free to the public. But, seriously, a little more effort on the instructions might go a long way to reducing the number of issues that are reported.

**Comment by iensen** [comment]
@Smit-tay ,

The instruction code vscode-ccls means you need to open command line and run that command. It also assumes that 

(a) you have code installed
(b) you have vscode-ccls in the folder where you run this command from.

It is a common knowledge that, unless otherwise specified, any instruction needs to be run from command line.  

Now that you know this, feel free to improve what is written. Frankly speaking, I don't see how to do it and I found what is written pretty clear. This is unfortunately the culture, especially in open source. Nobody writes manuals unless they are absolutely sure nobody else will ever understand. The good thing about open source is that you can spend a couple of days and study all the code how it needs to be configured and work. People find it fun. And, if you plan to really use this software heavily, you will need to do it anyways! Nothing is perfect and some slight tweaks might be needed (some of which can be pushed to this repo/suggested to the author). I personally this code base reasonably well written to be able to do it to some extent.

**Comment by pianocomposer321** [comment]
> It is a common knowledge that, unless otherwise specified, any instruction needs to be run from command line.

I disagree. Maybe you and I know that, but, obviously, not everybody does. Every other manual I've read has made it perfectly clear what commands are meant to be run in the terminal.

> Nobody writes manuals unless they are absolutely sure nobody else will ever understand.

Also not true. Manuals are written for many reasons. In this case, the manual is for installation, which, by the way, is another thing that I find annoying - why not just make an installer on the releases page?

> The good thing about open source is that you can spend a couple of days and study all the code how it needs to be configured and work. People find it fun.

I don't!
If I want a coding tool, I'm on GitHub to install it, not to poke around its source code.

**Comment by Smit-tay** [comment]
> It is a common knowledge that, unless otherwise specified, any instruction needs to be run from command line.

Absolutely false.  I have been a professional software developer since before the initial release of C++.  I have gained no such "common knowledge" in that time.

All it would take to make that instruction understandable is change:

> To load vscode-ccls without installing:

to

> To use the vscode-ccls extension without installing it, you can launch VS code from the comand-line with the name of the extension as a command argument:
  Example:  code vscode-ccls

Then a single sentence is explaining several things that are completly unclear in the original. 

1. That the instruction is to start VS Code (the executable image file name is "code") from the commandline.  
2. That VS Code can be provided the vscode-ccls extension as a command argument to load only that extension. 
3. That this method enables the use of an extension without "installing" that extension.

But, I suspect there is a problem lurking there.  If the extension is not installed, how would VS Code find it ?  I think that the path to the uninstalled extension would normally have to be provided.  Is that correct ?

Also, the next line in the "common sense" instructions, appears to be incorrect:

> Press F5

This is a horrible instruction.  Instructions should explain the purpose of actions.

example:

> You  should now configure the vscode-ccls plugin.  Press the F5 button,  to configure.

Furthermore, on my installation of VS-Code, pressing F5 launched the default debugger.  I didn't configure that, so, perhaps the instructions are actually incorrect anyway.

**Comment by madscientist** [comment]
Sounds like... you folks are the perfect people to fix the docs!

I spent some time doing that last year, and my changes were (mostly) accepted quickly.  There are still some confusing things (to me) in the docs (that I didn't understand so I couldn't clearly document) and since I use Emacs I didn't even look at the instructions for other editors like VS Code.

But since you know what you want the docs to say why not submit a PR?

**Comment by pianocomposer321** [comment]
@madscientist,

I agree, and @Smit-tay can certainly do that if he wishes. I, for one, have never used GitHub for anything other than installing programs and submitting issues for them, and I've never submitted a PR in my life. Until recently, I didn't even know what a PR was. XD

Also, I still don't understand what the instructions are trying to say, so I can't exactly change them. A while after submitting this issue, I gave up on ccls. I had been using either the neovintageous plugin for sublime text 3, or neovim. I don't remember which, I kept switching between them. Anyway, now I'm using vscode, which has fine lsp support for C/C++, so I'm not using ccls.

**Comment by madscientist** [comment]
Well, it's a great time to learn some new things!!  It won't take long, then you can be a participant in F/OSS in addition to a user.  For the docs it's even simpler as you can edit them online (see the *Edit* button in the upper right) you don't have to check them out and edit them somewhere else.

It may well be that many VScode users made the same choice you did and switched to something else, and so the docs have never been improved.  That's fine, but no one is getting paid to make these projects better so unless someone puts in some effort, they won't improve.  The last I heard MaskRay was using Emacs, so support for other editors (particularly docs) need to be contributed by their users.

**Comment by Smit-tay** [comment]
I have already update the documetnation as I have indicated.

I didn't even realize that was possible until today.

**Comment by iensen** [comment]
> Also, the next line in the "common sense" instructions, appears to be incorrect:
> 
> Press F5
> 
> This is a horrible instruction. Instructions should explain the purpose of actions.
> 
> example:
> 
> You should now configure the vscode-ccls plugin. Press the F5 button, to configure.
>Furthermore, on my installation of VS-Code, pressing F5 launched the default debugger. I didn't >configure that, so, perhaps the instructions are actually incorrect anyway.

I agree this was a horrible instruction, however, I believe it was correct, and now it is not. I don't use VS code much, so, I might be wrong, but, I believe, the purpose of F5 was to start a new instance of vscode where the plugin is 'temporary' installed, without doing it from the marketplace.

What's written now is, clearly, incorrect. Just starting vscode with vscode-ccls argument is not doing anything.

**Comment by iensen** [comment]
@Smit-tay 

Attached is a short video explaining the original instruction.
(Sorry, I could not attach .mp4 here).

Originally, I am in a folder where I have vscode-ccls (github repository).
I run code vscode-ccls to open vscode with vscode-ccls project.

Then, around 0:16, I press F5. This launches the debugger (there are some errors because I don't have all the nodejs, etc, installed, but let's ignore it). Note that when I click "Debug Anyway", it launches a new instance of vscode with special "Extension Development Host" title. My understanding is that this is  vscode with vscode-ccls extention "temporarily installed".


[vid.zip](https://github.com/MaskRay/ccls/files/4478982/vid.zip)

**Comment by iensen** [comment]
I have edited the instructions to make this paragraph (starting vscode-ccls without installing it) more clear (hopefully).

To be honest, I think, that we shouldn't talk about how to start vscode without installing it in this wiki at all.

It requires a lot of other things installed (node-js, typescript,etc), and should probably only be used to DEBUG vscode-ccls by those who want to develop the extension. So, I think this part should be moved to https://github.com/MaskRay/vscode-ccls. Any objections?

**Comment by Smit-tay** [comment]
I don't understand why you are launching the debugger (F5)

Surely the first thing that should be done is to configure the plug-in.

**Comment by iensen** [comment]
@Smit-tay ,

In short, I am launching the debugger to get a running intstance of vscode that has the plugin installed.

My vscode doesn't have the plugin installed, and I didn't download it from the marketplace. When I launch the debugger, a new instance of vscode is shown up (called "Extension Development Host"). It should have the plugin installed.

Please refer to https://code.visualstudio.com/api/get-started/your-first-extension for more details on how to run and develop extensions.

**Comment by iensen** [comment]
@Smit-tay ,

I may be wrong, but I think what you are missing is the following:

When I run the command 

code vscode-ccls, 

vscode-ccls is a relative path to the plugin source code. It is not a fixed name I can use to launch vscode with only that extension.

**Comment by MaskRay** [comment]
I noticed that `@Smit-tay` and `@findNextStep` have improved https://github.com/MaskRay/ccls/wiki/Visual-Studio-Code Thanks a lot for that!

As Paul said above, we can easily become a participant in F/OSS in addition to a user. Documentation can be an easy starting step but can still be very helpful for the posterity.

**Comment by pianocomposer321** [comment]
Thank you so much @Nazeehe! After yet another failed attempt to get clangd to recognize my MinGW headers, I decided to give ccls another try, following your instructions. I am happy to announce that, after about 3 hours of waiting for the ninja command to finish (Ok, maybe that was a bit of an exaggeration), it has successfully built. I then added the directory to my PATH, and it's working with coc.nvim like a charm!

Thanks again!
