### ISSUE TITLE
slow index load when compile with clang9

### ISSUE THREAD

**Issue by findNextStep** [MaskRay/ccls#585]
I have use ccls in mac for long time and find it take long time when we use clang9 with ccls

## way to recurrent
```
cmake -DCMAKE_BUILD_TYPE=Release -H. -Bbuild/test9 -DCMAKE_CXX_FLAGS=-O3 -DCMAKE_PREFIX_PATH=/usr/local/Cellar/llvm/9.0.1/lib/cmake/clang/
cmake -DCMAKE_BUILD_TYPE=Release -H. -Bbuild/test8 -DCMAKE_CXX_FLAGS=-O3 -DCMAKE_PREFIX_PATH=/usr/local/Cellar/llvm@8/8.0.1_1/lib/cmake/clang
make -C ./build/test9 -j
make -C ./build/test8 -j
time ./build/test8/ccls -index=./ -init="{\"compilationDatabaseDirectory\":\"./build/Debug\",\"cache\":{\"directory\":\"./.ccls-cache8\",\"format\":\"binary\",\"hierarchicalPath\":false,\"retainInMemory\":2},\"clang\":{\"extraArgs\":[\"-isystem\",\"/usr/local/Cellar/llvm/9.0.0_1/include/c++/v1\",\"-Wold-style-cast\"],\"resourceDir\":\"/usr/local/Cellar/llvm/9.0.0_1/lib/clang/9.0.0\"},\"index\":{\"threads\":29}}" 
time ./build/test9/ccls -index=./ -init="{\"compilationDatabaseDirectory\":\"./build/Debug\",\"cache\":{\"directory\":\"./.ccls-cache9\",\"format\":\"binary\",\"hierarchicalPath\":false,\"retainInMemory\":2},\"clang\":{\"extraArgs\":[\"-isystem\",\"/usr/local/Cellar/llvm/9.0.0_1/include/c++/v1\",\"-Wold-style-cast\"],\"resourceDir\":\"/usr/local/Cellar/llvm/9.0.0_1/lib/clang/9.0.0\"},\"index\":{\"threads\":29}}" 
```

it`s slow not only in index, but also when ccls load cache, and with clang9 , the cpu usage is low.
here is the result

![llvm9+ccls](https://user-images.githubusercontent.com/26270464/75957022-1f658700-5ef4-11ea-8248-83a177042021.png)
![llvm8+ccls](https://user-images.githubusercontent.com/26270464/75957029-21c7e100-5ef4-11ea-8b4c-680c3132bed5.png)

it seem that we can recurrent in linux.

**Comment by joelhock** [comment]
could it be that we use background priority for the background threads when compiled against clang 9?
https://github.com/MaskRay/ccls/commit/64e3e8f2508d141094a640f9116411a15be9cae4
to help narrow down the issue, you might try disabling that code and see if it helps.

**Comment by findNextStep** [comment]
> could it be that we use background priority for the background threads when compiled against clang 9?
> [64e3e8f](https://github.com/MaskRay/ccls/commit/64e3e8f2508d141094a640f9116411a15be9cae4)
> to help narrow down the issue, you might try disabling that code and see if it helps.

yes. It work
can we revert it?

**Comment by MaskRay** [comment]
@eklitzke

**Comment by joelhock** [comment]
the llvm source for llvm::set_thread_priority() has these comments that might explain why this is happening on mac:

>   #elif defined(__APPLE__)
   // https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/getpriority.2.html
  // When setting a thread into background state the scheduling priority is set
  // to lowest value, disk and network IO are throttled. Network IO will be
  // throttled for any sockets the thread opens after going into background
  // state. Any previously opened sockets are not affected.
  // https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/getiopolicy_np.3.html
  // I/Os with THROTTLE policy are called THROTTLE I/Os. If a THROTTLE I/O
  // request occurs within a small time window (usually a fraction of a second)
  // of another NORMAL I/O request, the thread that issues the THROTTLE I/O is
  // forced to sleep for a certain interval. This slows down the thread that
  // issues the THROTTLE I/O so that NORMAL I/Os can utilize most of the disk
  // I/O bandwidth.

**Comment by MaskRay** [comment]
Thanks for everyone discussing this issue. Essentially reverted the change for macOS (I wanted to make [0.20190823.6](https://github.com/MaskRay/ccls/releases/tag/0.20190823.6) buildable with clang 10 and 0.20190314.5 buildable with clang 9, so I rebased master)
