### ISSUE TITLE
Compilation database when working in headers

### ISSUE THREAD

**Issue by beojan** [MaskRay/ccls#644]
When working in header files in my project, ccls flags errors because it doesn't know about the compiler options any file that header is included in would be compiled with.

I'm not really sure how this could be fixed, since the compilation database doesn't include headers. Any ideas?

**Comment by myrgy** [comment]
you may add one cpp file which includes all you files

**Comment by beojan** [comment]
I already have `.cpp` files in the project that use these headers.

**Comment by robbert-vdh** [comment]
I'm not sure what exactly changed, but I've also been having this issue since the most recent [Manjaro update](https://forum.manjaro.org/t/stable-update-2020-05-31-kernels-toolchain-kde-apps-gnome-cinnamon-deepin/145562). I have not had any issues before that, but now opening any random header file that previously would not produce any warnings or errors at all with the same `compile_commands.json` file now always results in at least a `#pragma once in main file` warning and file not found error when including a header that's not in the system include path. Since and neither LLVM nor ccls have been updated I can only image that this is some kind of compatibility issue with GCC 10.

**Comment by MaskRay** [comment]
From the discussions this appears to be working. Please include more information (see the issue template) if you want to reopen it.
