### ISSUE TITLE
Questions on Cmake Build

### ISSUE THREAD

**Issue by LeeRuns** [MaskRay/ccls#691]
Hey there, great library  👍 .

Your cmake setup is pretty interesting, but there are a couple  of points of confusion for me.  I looks through cmake docs and didn't find immedeate answers so i through i would ask.  Please be patient w/me, not being nit picky just curious.

```
cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/local/Cellar/llvm/<Your Version>/lib/cmake
```

1. _Why are you calling -h that is the help menu?_
2. _Why no space between --H and . seems like that would clarify, unless -H. has different meaning than -H . ?_
3. _Why set the cmake premix path, it knows where it is? _ 

Thanks!!!

**Comment by madscientist** [comment]
You can learn the reasons for these just by trying them out, but:

The `-H<dir>` form used here is very old, and very deprecated.  It's so old that you can't find it in any of the releases that still have documentation published at the cmake site.  However, it still works even though it's not documented anymore.  Basically this means the same thing as not providing a `-H` option at all: it tells cmake where to look for the source tree.

So, `-H.` is the same as just specifying `.` and `-H` with no argument shows help.

You can't put a space between them because then it's considered two separate arguments: a help option plus a `.` command.

I think the sample command line here should be modified to be more modern but ISTR that @MaskRay prefers the old style with explicit options.

As for the cmake prefix, that's not to find cmake, that's to find LLVM's cmake configuration.

**Comment by LeeRuns** [comment]
Well that makes me feel better, because I searched and could not find that answer.  Thank you... so then why not...seems to match modern cmake.   

This may all seem stylistic, but if your having issues with trying to compile or get cmake to find your setup correctly, then it is logical to look at what cmake is doing.  Then if there is no documentation to explain that. Well then it's no good.
Seems like this is just vanilla cmake 
```
cmake . -B Release 
```

for example with cmake, and msys setup of mingw of clang+llvm then it is just one command.  Finally the DCMAKE_INSTALL_PREFIX is not recommended by kitware, instead use --prefix with the install command.  If we write them as discrete steps is becomes very clear to the reader.

## windows
```
cmake  -S .. -B Release -G Ninja && cmake --build . && cmake --install .  --prefix C:/usr/local/bin
```
## unix
```
cmake  -S .. -B Release && cmake --build . && cmake --install .  --prefix /usr/local/bin
```

**Comment by bfrg** [comment]
The `-H` and `-B` options were only for internal use.

Source: https://cmake.org/pipermail/cmake-developers/2016-June/028844.html

**Comment by LeeRuns** [comment]
So I don't see why I would not just update to fit modern cmake, as there is no assurance that those will work later.  Sound Good?

**Comment by MaskRay** [comment]
Thanks for the responses! The thread at https://cmake.org/pipermail/cmake-developers/2016-June/028844.html has well summarized the convenience of -H + -B :)

> Next issue is that this command change directory, how can I move back to the directory where I was working on?

We can stick with -H + -B until they are entirely dead;-)
