### ISSUE TITLE
Where do you build CCLS, and what are the prefix paths?

### ISSUE THREAD

**Issue by ItsCubeTime** [MaskRay/ccls#728]
https://github.com/MaskRay/ccls/wiki/Build So, obv Im trying to install CCLS

Im on Windows, could someone explain to me what Im supposed to be doing after that I've built Clang/LLVM from source?

It says:
```
# Download ccls
cd ccls
cmake -H. -BRelease -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_PREFIX_PATH="D:/llvm/Release;D:/llvm/Release/tools/clang;D:/llvm;D:/llvm/tools/clang"
ninja -C Release
```
But like, download, ccls (Is it just supposed to be in its own directory or am I supposed to place it inside of the LLVM dir somewhere?)? And then what are the `DCMAKE_PREFIX_PATH=` flags?

Also, can I just download the whole ccls repo directly from my browser or will I need to clone with git?

**Comment by FancyBanana** [comment]
Since the author is adamantly stubborn against including a 7mb binary **THAT HE ALREADY BUILDS WITH APPVEYOR** in his releases, I made my own fork were I make builds from time to time. https://github.com/FancyBanana/ccls/releases/tag/win10-5.12.20

**Comment by ItsCubeTime** [comment]
> Since the author is adamantly stubborn against including a 7mb binary **THAT HE ALREADY BUILDS WITH APPVEYOR** in his releases, I made my own fork were I make builds from time to time. https://github.com/FancyBanana/ccls/releases/tag/win10-5.12.20

Haha thanks 👍 

I would still wanna know how Im supposed to build this as Ive already built Clang and LLVM.

I were actually sitting figuring on this right as you posted. Currently, I havent set my source built clang version as the one in PATH. How would I tell Cmake to use my source version?

Also I dont quite understand what this: -DCMAKE_PREFIX_PATH="D:/llvm/Release;D:/llvm/Release/tools/clang;D:/llvm;D:/llvm/tools/clang"

is, why are there 3 paths here? Should I have 3 paths? In my case Im on Windows and I have my source build in: C:\Program Files\LLVM 11.0.0 Source\llvm\tools\clang

**Comment by ItsCubeTime** [comment]
I should say, I've barely ever used git bash before, so Im not familiar at all with it. So I would be very glad if you could give me some more laboratory example or give some kind of explanation here.

Ive installed all the build requirements stated here on Github and setup environment variables for everything but my source built Clang

**Comment by ItsCubeTime** [comment]
Also, I used 

git clone https://github.com/MaskRay/ccls.git

to download ccls to: C:\Program Files\CCLS\ccls (Yes, CCLS\ccls 💯 )

**Comment by ItsCubeTime** [comment]
Also, heres what Git bash returns when I attempt building it:

https://pastebin.com/Yr3F5t7p

**Comment by MaskRay** [comment]
About `cmake -H. -BRelease -G Ninja -DCMAKE_BUILD_TYPE=Release`. Its my personal preference that having the build directories directly under the project root and calling the typical release build directory `$srcdir/Release` ... You can freely use other directories, like `build/` as someone else uses. I don't use `build/` because I want to emphasize the difference between Debug and Release. Actually for some projects I have many build directories and I place them under `$srcdir/out/`...

> Also I dont quite understand what this: -DCMAKE_PREFIX_PATH="D:/llvm/Release;D:/llvm/Release/tools/clang;D:/llvm;D:/llvm/tools/clang"

Originally I found that you need both build directories and llvm and clang source directories in `CMAKE_PREFIX_PATH`.
Seems that just having the build directory works. Updated [wiki/Build](https://github.com/MaskRay/ccls/wiki/Build)
