### ISSUE TITLE
Generated json contains \u0000 and causes lsp-mode / emacs-ccls to fail parsing

### ISSUE THREAD

**Issue by triplejam** [MaskRay/ccls#768]
### Observed behavior

When lsp-treemacs-symbols is called, or if lsp-ui is installed in emacs, certain c++ files will cause emacs to show a warning about failing to parse json. If lsp-treemacs-symbols was called it will be empty. 

I think it is related to user-defined conversion functions and or typedefs.

### Expected behavior

JSON would be parsed successfully and there would be no warning. The symbols tree would be complete.

### Steps to reproduce

Small example which reproduces the issue:

```cpp 
struct A
{
    typedef unsigned int sz;
    operator sz() const { return 0; }
}; 
```

If `int` is used instead of `unsigned int` it works fine. Alternatively if `explicit` is put before operator it works.

### System information

* ccls version 0.20201219-5-g4cd308d7
* clang version: 11.0.1
* OS: OSX 11.2.1
* Editor: Emacs 27.1
* Language client (and version): ccls 20200820.308

**Comment by TheJJ** [comment]
I got the same on latest git 4cd308d7.

It looks like some out-of-bounds string read.

```cpp
class ... {
[snip]
	operator T() const {
		return this->value;
	}
[snip]
}
```

```python
 {'children': [],
  'detail': 'operator T() const',
  'kind': 6,
  'name': 'operator T() const\x00std::__s',
  'range': {'end': {'character': 2, 'line': 63},
            'start': {'character': 1, 'line': 61}},
  'selectionRange': {'end': {'character': 11, 'line': 61},
                     'start': {'character': 1, 'line': 61}}},
```

the json contains the 0-byte, likely it's the terminator of the function name, since there's more stuff starting after it.

**Comment by orlandini** [comment]
While this is not solved, the following snippet in , originally posted by @yyoncho in https://github.com/emacs-lsp/lsp-mode/issues/2681#issuecomment-792563858, is a workaround:
```
(advice-add 'json-parse-string :around 
            (lambda (orig string &rest rest)
              (apply orig (s-replace "\\u0000" "" string)
                     rest)))
```

**Comment by madscientist** [comment]
It seems like that snippet isn't really quite correct: it surely will get rid of the warnings but if the problem is that extra text is being included the more correct thing would be to remove all text starting with \00 up to the end of the string, rather than deleting the \00 by itself.  Otherwise the "name" field will contain garbage.

Of course an incorrect name is an improvement over the warnings, and of course the correct solution will be to fix ccls (or whatever aspect of clang/llvm is generating these incorrect strings).  Just sayin'...

**Comment by TheJJ** [comment]
My workaround variant that does null-byte termination within these json-strings is:
```elisp
(advice-add 'json-parse-string :around
            (lambda (orig string &rest args)
              (apply orig                                                                            
                     (replace-regexp-in-string "\\\\u0000.*?\"" "\"" string)
                     args)))
```

**Comment by zhangjunphy** [comment]
After some debugging it seems the out-of-bound read is caused by this line https://github.com/MaskRay/ccls/blob/4cd308d7fd71bc82376520d9e042fe339f01b8ef/src/indexer.cc#L476
The name returned by clang is not always a prefix for the identifier, at least not for operators. In fact it gives `operator unsigned int` for `sz` in the above example, which is 2 bytes longer than `operator sz() const`.
