### ISSUE TITLE
The command given in the MacPorts section doesn't build

### ISSUE THREAD

**Issue by wyuenho** [MaskRay/ccls#80]
This is the list of commands I've used:

```
$ git clone --recursive git@github.com:MaskRay/ccls.git
$ cd ccls
$ cmake -H. -BRelease -DSYSTEM_CLANG=on -DCMAKE_CXX_COMPILER=clang++-mp-6.0 -DCMAKE_PREFIX_PATH=/opt/local/libexec/llvm-6.0/lib -DLLVM_ENABLE_RTTI=on -DUSE_SHARED_LLVM=on
$ cmake --build Release
```

This is the output:

```
Scanning dependencies of target ccls
[  1%] Building CXX object CMakeFiles/ccls.dir/third_party/siphash.cc.o
[  3%] Building CXX object CMakeFiles/ccls.dir/src/clang_complete.cc.o
In file included from /Users/wyuenho/ccls/src/clang_complete.cc:16:
In file included from /Users/wyuenho/ccls/src/clang_complete.hh:18:
/Users/wyuenho/ccls/src/clang_tu.h:19:10: fatal error: 'clang/Basic/LangOptions.h' file not found
#include <clang/Basic/LangOptions.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/ccls.dir/src/clang_complete.cc.o] Error 1
make[1]: *** [CMakeFiles/ccls.dir/all] Error 2
make: *** [all] Error 2
```

It seems like it's still trying to search for the local clang that it didn't download.

**Comment by MaskRay** [comment]
`-DCMAKE_PREFIX_PATH=` should be a `;`-separated list where you can find:

* `include/llvm/Config/config.h`
* `include/clang/Config/config.h`
* `lib/libclangIndex.so`
* `lib/libLLVM{Support,...}.so` or `lib/libLLVM{Support,...}.a` or `lib/libLLVM.so`

**Comment by wyuenho** [comment]
Ah I see, the wiki is wrong then. I've updated the wiki to reflect this. Thanks.

**Comment by wyuenho** [comment]
FYI, the prefix path should be `/opt/local/libexec/llvm-6.0`

**Comment by MaskRay** [comment]
Sorry I might have scrubbed your wiki change when I was changing `Build.md`. Can you check again if the instruction works?

`cmake -H. -BRelease -DSYSTEM_CLANG=on -DCMAKE_CXX_COMPILER=clang++-mp-6.0 -DCMAKE_PREFIX_PATH=/opt/local/libexec/llvm-6.0 -DLLVM_ENABLE_RTTI=on -DUSE_SHARED_LLVM=on`

**Comment by MaskRay** [comment]
I would like to know:

* memory footprint
* diagnostics (I added debounce mechanism yesterday) this affects CPU time
* `$ccls/member`: it can list member functions/nested classes as well as member variables (see more in https://github.com/MaskRay/ccls/wiki/Emacs#cross-reference-extensions)
* performance of `ccls-sem-highlight-method` (optimized)
* robustness of pipeline

If you don't mind sharing your experience with other alternatives :)

**Comment by wyuenho** [comment]
I don't know how to give you these stats, if you can write something on the wiki, maybe I can help then

**Comment by MaskRay** [comment]
There was a redundant cache reloading issue which has been introduced from last release caused by refactoring of pipeline (the component that does dependency tracking and dispatches indexing tasks parallelly). It should have been fixed in the latest release https://github.com/MaskRay/ccls/releases/tag/0.20180924

Some random notes about things I want to measure:

`strace -ttfe read,write -p $(pgrep -fn Release/ccls)` see the latency between a request and its response.

@scturtle 's
`CPUPROFILE=ccls.prof CPUPROFILESIGNAL=12 CPUPROFILE_FREQUENCY=1000`, open a file in emacs; `killall -12 ccls`

Linux specific:
* `sysdig -As9999 --unbuffered "proc.exe contains ccls and fd.type=pipe"`

* `perf record -a --call --call-graph $(pgrep -fn Release/ccls)`
